---
# Deploy procedures
# -----------------
#
# We need to process theme assets for both storefront-master and our Tonik
# based child theme. We run the install and build commands locallaly and then
# use the Ansible syncronize command to upload the compiled files to the server.

# Storefront
- name: Install npm dependencies
  command: npm install
  connection: local
  args:
    chdir: "{{ project_local_path }}/web/app/themes/storefront-master"

- name: Install Composer dependencies
  command: composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts
  args:
    chdir: "{{ deploy_helper.new_release_path }}/web/app/themes/storefront-master"

- name: Compile assets for production
  command: grunt
  connection: local
  args:
    chdir: "{{ project_local_path }}/web/app/themes/storefront-master"

- name: Copy production assets
  synchronize:
    src: "{{ project_local_path }}/web/app/themes/storefront-master/assets/"
    dest: "{{ deploy_helper.new_release_path }}/web/app/themes/storefront-master/assets/"
    group: no
    owner: no
    rsync_opts: --chmod=Du=rwx,--chmod=Dg=rx,--chmod=Do=rx,--chmod=Fu=rw,--chmod=Fg=r,--chmod=Fo=r

# StayDry/Tonik

